import type { ConnectorCredentialAssignment } from "../../api/credentialAssignments";
import { targetConfigurationBinding as binding } from "./testTargetBindingFixture";

export const credentialAssignment = {
  assignment_id: "connector-credential-assignment.test",
  schema_version: "atlas.connector-credential-assignment.v1",
  version: 1,
  source_target_binding_id: binding.binding_id,
  source_target_binding_digest: binding.canonical_digest,
  organization_id: binding.organization_id,
  environment_id: binding.environment_id,
  package_digest: binding.package_digest,
  connector_id: binding.connector_id,
  release_version: binding.release_version,
  manifest_digest: binding.manifest_digest,
  instance_id: binding.instance_id,
  instance_key: binding.instance_key,
  display_name: binding.display_name,
  owner_id: binding.owner_id,
  target_profile_id: binding.target_profile_id,
  target_profile_digest: binding.target_profile_digest,
  site_id: binding.site_id,
  target_type: binding.target_type,
  target_product: binding.target_product,
  credential_profile_id: "connector-credential-profile.development-storage-reader",
  credential_profile_digest: "0279f90b6ac015d81a154b723ddbd9bc687b6fccdf286b50cb99ca71e66e1867",
  credential_class: "credential.vendor-api",
  authentication_method: "authentication.api-token",
  vendor_role: "vendor-role.storage-reader",
  privilege_class: "privilege.read-only",
  rotation_state: "rotation.current",
  revocation_state: "revocation.active",
  next_rotation_at: "2026-08-10T00:00:00Z",
  credential_policy_id: "connector-credential-assignment-policy.development",
  credential_policy_digest: "a9ba1da0bb85635e926d69e839c38952153d4349b9e456921101f3b0799f2cca",
  credential_policy_version: "version.1.0",
  assignment_version: 1,
  instance_state: "disabled_credentials_assigned",
  assigned_by: "subject.connector-independent-credential-assigner",
  purpose: "Assign governed credential metadata without secret or runtime access.",
  assigned_at: "2026-08-06T00:00:00Z",
  canonical_digest: "a".repeat(64),
  package_installed: true,
  instance_created: true,
  target_configured: true,
  eligible_for_credential_governance: true,
  credential_references_assigned: true,
  eligible_for_configuration_validation: true,
  promotion_blocked: false,
  credentials_resolved: false,
  connector_enabled: false,
  runtime_trust_granted: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorCredentialAssignment;
