import type {
  ConnectorBoundedInvocationInventoryItem,
  ConnectorBoundedInvocationOption,
} from "../../api/boundedInvocations";
import { invocationAuthorizationInventoryItem } from "./testInvocationAuthorizationFixture";

export const boundedInvocationOption = {
  source_authorization_id: invocationAuthorizationInventoryItem.authorization_id,
  source_authorization_digest: invocationAuthorizationInventoryItem.canonical_digest,
  package_digest: "f".repeat(64),
  capability_id: invocationAuthorizationInventoryItem.capability_id,
  capability_class: invocationAuthorizationInventoryItem.capability_class,
  required_permission: "storage.health.read",
  invocation_policy_id: "connector-bounded-invocation-policy.development",
  invocation_policy_digest: "1".repeat(64),
  invocation_policy_version: "policy-v1",
  invocation_policy_expires_at: "2030-01-01T00:30:00Z",
  required_assurance_level: "single_factor",
  maximum_timeout_seconds: 30,
  maximum_output_bytes: 262144,
  maximum_observations: 100,
  resulting_instance_state: "enabled_bounded_capability_invocation_completed",
  irreversible_consumption_required: true,
  automatic_retry_allowed: false,
  target_connected: false,
  reusable_session_available: false,
  scheduled: false,
  evidence_ingested: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorBoundedInvocationOption;

export const boundedInvocationInventoryItem = {
  invocation_id: "connector-bounded-invocation.test",
  schema_version: "atlas.connector-bounded-invocation.v1",
  version: 1,
  source_authorization_id: invocationAuthorizationInventoryItem.authorization_id,
  source_authorization_digest: boundedInvocationOption.source_authorization_digest,
  package_digest: boundedInvocationOption.package_digest,
  capability_id: boundedInvocationOption.capability_id,
  capability_class: boundedInvocationOption.capability_class,
  required_permission: boundedInvocationOption.required_permission,
  output_schema_digest: "0".repeat(64),
  result_policy_digest: "a".repeat(64),
  invocation_policy_id: boundedInvocationOption.invocation_policy_id,
  invocation_policy_digest: boundedInvocationOption.invocation_policy_digest,
  invocation_policy_version: boundedInvocationOption.invocation_policy_version,
  normalized_redacted_result_digest: "2".repeat(64),
  observation_count: 1,
  output_bytes: 256,
  instance_state: "enabled_bounded_capability_invocation_completed",
  started_at: "2026-08-25T00:00:04Z",
  completed_at: "2026-08-25T00:00:04.025Z",
  canonical_digest: "3".repeat(64),
  authorization_consumed: true,
  target_connection_opened: true,
  capability_invoked: true,
  result_received: true,
  result_validated: true,
  result_redacted: true,
  target_session_closed: true,
  delivery_channel_closed: true,
  lease_revocation_confirmed: true,
  target_connected: false,
  reusable_session_available: false,
  scheduled: false,
  evidence_ingested: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorBoundedInvocationInventoryItem;
