import type { ConnectorPackageSigningReceipt } from "../../api/packageSigning";

export const receipt = {
  receipt_id: "connector-package-signing-receipt.test",
  schema_version: "atlas.connector-package-signing-receipt.v1",
  version: 1,
  envelope: {
    envelope_id: "connector-package-signing-envelope.test",
    schema_version: "atlas.connector-package-signing-envelope.v1",
    source_attestation_report_id: "connector-publisher-attestation.test",
    source_attestation_report_digest: "a".repeat(64),
    package_digest: "b".repeat(64),
    publisher_id: "publisher.atlas-labs",
    connector_id: "connector.hitachi-ops-center",
    release_version: "version.1.0.0",
    provenance_digest: "c".repeat(64),
    signing_policy_id: "connector-package-signing-policy.development",
    signing_policy_digest: "d".repeat(64),
    signer_profile_id: "signer-profile.nonproduction-hmac",
    requested_by: "subject.package-independent-signing-requester",
    canonical_digest: "e".repeat(64),
  },
  signature: {
    signer_profile_id: "signer-profile.nonproduction-hmac",
    signer_workload_id: "workload.connector-package-signer",
    key_id: "key.connector-package-signing.nonproduction",
    algorithm: "algorithm.hmac-sha256-nonproduction",
    envelope_digest: "e".repeat(64),
    signature_digest: "f".repeat(64),
    issued_at: "2026-08-06T00:00:00Z",
    expires_at: "2026-08-13T00:00:00Z",
    signature_verified: true,
  },
  organization_id: "organization.development",
  environment_id: "environment.development",
  requested_by: "subject.package-independent-signing-requester",
  signing_policy_id: "connector-package-signing-policy.development",
  signing_policy_digest: "d".repeat(64),
  signed_at: "2026-08-06T00:00:00Z",
  canonical_digest: "1".repeat(64),
  publisher_attested: true,
  package_signed: true,
  eligible_for_registry_governance: true,
  promotion_blocked: false,
  reused: false,
  connector_registered: false,
  connector_installed: false,
  connector_enabled: false,
  target_configured: false,
  credentials_resolved: false,
  runtime_trust_granted: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorPackageSigningReceipt;
