import type {
  ConnectorRuntimeActivationInventoryItem,
  ConnectorRuntimeActivationOption,
} from "../../api/runtimeActivations";
import { secretBrokerageAuthorizationInventoryItem as brokerage } from "./testSecretBrokerageFixture";

export const runtimeActivationOption = {
  source_brokerage_authorization_id: brokerage.authorization_id,
  source_brokerage_authorization_digest: "6".repeat(64),
  package_digest: "7".repeat(64),
  activation_profile_id: "connector-runtime-activation-profile.synthetic-isolated",
  activation_profile_digest: "8".repeat(64),
  activation_profile_expires_at: "2030-01-01T00:00:00Z",
  activation_policy_id: "connector-runtime-activation-policy.development",
  activation_policy_digest: "9".repeat(64),
  activation_policy_version: "policy-v1",
  activation_policy_expires_at: "2030-01-01T00:00:00Z",
  required_assurance_level: "single_factor",
  health_probe_ids: ["health.local.package", "health.local.runtime"],
  resulting_instance_state: "enabled_runtime_healthy",
  secret_lease_issued: true,
  credentials_resolved: true,
  runner_started: true,
  package_loaded: true,
  runtime_health_verified: true,
  delivery_channel_closed: true,
  lease_revocation_confirmed: true,
  eligible_for_target_session_authorization: true,
  target_connected: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  capability_invoked: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorRuntimeActivationOption;

export const runtimeActivationInventoryItem = {
  activation_id: "connector-runtime-activation.test",
  source_brokerage_authorization_id: brokerage.authorization_id,
  connector_id: brokerage.connector_id,
  release_version: brokerage.release_version,
  instance_id: brokerage.instance_id,
  display_name: brokerage.display_name,
  activation_profile_id: runtimeActivationOption.activation_profile_id,
  activation_policy_id: runtimeActivationOption.activation_policy_id,
  activation_policy_version: runtimeActivationOption.activation_policy_version,
  activation_adapter_id: "connector-runtime-activation-adapter.synthetic",
  health_probe_results: runtimeActivationOption.health_probe_ids.map((probe_id) => ({
    probe_id,
    outcome: "health.passed" as const,
  })),
  instance_state: "enabled_runtime_healthy",
  activated_by: "subject.connector-runtime-activator",
  purpose: "Activate exact isolated runtime and verify signed local health without target access.",
  activated_at: "2026-08-24T00:00:00Z",
  healthy_at: "2026-08-24T00:00:01Z",
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  secret_brokerage_governed: true,
  credential_resolution_authorized: true,
  secret_lease_issued: true,
  credentials_resolved: true,
  runner_started: true,
  package_loaded: true,
  runtime_health_verified: true,
  lease_delivery_completed: true,
  delivery_channel_closed: true,
  lease_revocation_confirmed: true,
  eligible_for_target_session_authorization: true,
  target_connected: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  capability_invoked: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorRuntimeActivationInventoryItem;
