import type {
  OperationalKnowledgeReviewerAssignmentInventoryItem,
  OperationalKnowledgeReviewerAssignmentOption,
} from "../../api/reviewerAssignments";
import { knowledgeReviewRequestInventoryItem as reviewRequest } from
  "./testKnowledgeReviewRequestFixture";

export const reviewerAssignmentOption = {
  assignment_option_id: "operational-knowledge-reviewer-assignment-option.test",
  source_review_request_id: reviewRequest.review_request_id,
  source_review_request_digest: reviewRequest.canonical_digest,
  source_draft_id: reviewRequest.source_draft_id,
  knowledge_item_id: reviewRequest.knowledge_item_id,
  connector_id: reviewRequest.connector_id,
  instance_id: reviewRequest.instance_id,
  capability_id: reviewRequest.capability_id,
  assignment_policy_id: "operational-knowledge-reviewer-assignment-policy.development",
  assignment_policy_digest: "a".repeat(64),
  assignment_policy_version: "policy-v1",
  assignment_policy_expires_at: "2030-01-01T03:00:00Z",
  required_assurance_level: "single_factor",
  domain_track_code: "review-track.domain",
  security_track_code: "review-track.security",
  assignment_ttl_minutes: 1440,
  resulting_instance_state: "operational_knowledge_reviewers_assigned",
  resulting_domain_status: "assigned",
  resulting_security_status: "assigned",
  irreversible_claim_required: true,
  automatic_retry_allowed: false,
  review_requested: true,
  reviewer_assigned: true,
  content_inspection_opened: false,
  domain_review_completed: false,
  security_review_completed: false,
  knowledge_approved: false,
  knowledge_published: false,
  retrieval_published: false,
  model_context_available: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies OperationalKnowledgeReviewerAssignmentOption;

export const reviewerAssignmentInventoryItem = {
  assignment_set_id: "operational-knowledge-reviewer-assignment.test",
  schema_version: "atlas.operational-knowledge-reviewer-assignment.v1",
  version: 1,
  source_review_request_id: reviewRequest.review_request_id,
  source_review_request_digest: reviewRequest.canonical_digest,
  source_draft_id: reviewRequest.source_draft_id,
  source_draft_digest: reviewRequest.source_draft_digest,
  knowledge_item_id: reviewRequest.knowledge_item_id,
  draft_version_id: reviewRequest.draft_version_id,
  connector_id: reviewRequest.connector_id,
  instance_id: reviewRequest.instance_id,
  capability_id: reviewRequest.capability_id,
  title: reviewRequest.title,
  knowledge_lifecycle: "reviewer_assigned",
  classification: reviewRequest.classification,
  retention_policy_id: reviewRequest.retention_policy_id,
  domain_track_code: "review-track.domain",
  security_track_code: "review-track.security",
  domain_status: "assigned",
  security_status: "assigned",
  assignment_policy_id: reviewerAssignmentOption.assignment_policy_id,
  assignment_policy_digest: reviewerAssignmentOption.assignment_policy_digest,
  assignment_policy_version: reviewerAssignmentOption.assignment_policy_version,
  created_at: "2026-08-25T00:10:00Z",
  expires_at: "2026-08-26T00:10:00Z",
  instance_state: "operational_knowledge_reviewers_assigned",
  canonical_digest: "b".repeat(64),
  review_requested: true,
  reviewer_assigned: true,
  immutable_assignments_confirmed: true,
  encrypted_identity_references: true,
  transient_identity_buffers_erased: true,
  directory_channel_closed: true,
  content_inspection_opened: false,
  domain_review_completed: false,
  security_review_completed: false,
  correction_created: false,
  knowledge_approved: false,
  knowledge_published: false,
  chunks_created: false,
  embeddings_created: false,
  retrieval_published: false,
  model_context_available: false,
  graph_updated: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies OperationalKnowledgeReviewerAssignmentInventoryItem;
