import type {
  OperationalKnowledgeReviewRequestInventoryItem,
  OperationalKnowledgeReviewRequestOption,
} from "../../api/knowledgeReviewRequests";
import { evidenceKnowledgeDraftInventoryItem as draft } from "./testEvidenceDraftFixture";

export const knowledgeReviewRequestOption = {
  review_request_option_id: "operational-knowledge-review-request-option.test",
  source_draft_id: draft.draft_id,
  source_draft_digest: draft.canonical_digest,
  knowledge_item_id: "knowledge-item.operational-evidence.test",
  connector_id: draft.connector_id,
  instance_id: draft.instance_id,
  capability_id: draft.capability_id,
  orchestration_policy_id: "operational-knowledge-review-request-policy.development",
  orchestration_policy_digest: "d".repeat(64),
  orchestration_policy_version: "policy-v1",
  orchestration_policy_expires_at: "2030-01-01T02:00:00Z",
  required_assurance_level: "single_factor",
  classification: draft.classification,
  retention_policy_id: draft.retention_policy_id,
  domain_track_code: "review-track.domain",
  security_track_code: "review-track.security",
  assignment_strategy: "assignment-strategy.policy-controlled",
  sla_class: "sla.knowledge-review-standard",
  resulting_instance_state: "operational_knowledge_review_requested",
  resulting_domain_status: "awaiting_reviewer",
  resulting_security_status: "awaiting_reviewer",
  irreversible_claim_required: true,
  automatic_retry_allowed: false,
  review_requested: true,
  reviewer_assigned: false,
  content_inspection_opened: false,
  domain_review_completed: false,
  security_review_completed: false,
  knowledge_approved: false,
  knowledge_published: false,
  retrieval_published: false,
  model_context_available: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies OperationalKnowledgeReviewRequestOption;

export const knowledgeReviewRequestInventoryItem = {
  review_request_id: "operational-knowledge-review-request.test",
  schema_version: "atlas.operational-knowledge-review-request.v1",
  version: 1,
  source_draft_id: draft.draft_id,
  source_draft_digest: draft.canonical_digest,
  knowledge_item_id: knowledgeReviewRequestOption.knowledge_item_id,
  draft_version_id: "knowledge-draft-version.test",
  connector_id: draft.connector_id,
  instance_id: draft.instance_id,
  capability_id: draft.capability_id,
  title: draft.title,
  knowledge_lifecycle: "review_requested",
  classification: draft.classification,
  retention_policy_id: draft.retention_policy_id,
  retention_policy_digest: draft.retention_policy_digest,
  orchestration_policy_id: knowledgeReviewRequestOption.orchestration_policy_id,
  orchestration_policy_digest: knowledgeReviewRequestOption.orchestration_policy_digest,
  orchestration_policy_version: knowledgeReviewRequestOption.orchestration_policy_version,
  domain_track_code: knowledgeReviewRequestOption.domain_track_code,
  security_track_code: knowledgeReviewRequestOption.security_track_code,
  assignment_strategy: knowledgeReviewRequestOption.assignment_strategy,
  sla_class: knowledgeReviewRequestOption.sla_class,
  domain_status: "awaiting_reviewer",
  security_status: "awaiting_reviewer",
  manifest_bytes: 256,
  created_at: "2026-08-25T00:00:09Z",
  instance_state: "operational_knowledge_review_requested",
  canonical_digest: "e".repeat(64),
  review_requested: true,
  immutable_manifest_confirmed: true,
  encrypted_at_rest: true,
  transient_buffers_erased: true,
  artifact_channel_closed: true,
  reviewer_assigned: false,
  content_inspection_opened: false,
  domain_review_completed: false,
  security_review_completed: false,
  correction_created: false,
  knowledge_approved: false,
  knowledge_published: false,
  chunks_created: false,
  embeddings_created: false,
  retrieval_published: false,
  model_context_available: false,
  graph_updated: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies OperationalKnowledgeReviewRequestInventoryItem;
