import type { ConnectorTargetConfigurationBinding } from "../../api/targetConfigurations";
import { connectorInstanceRecord as instance } from "./testInstanceFixture";

export const targetConfigurationBinding = {
  binding_id: "connector-target-configuration-binding.test",
  schema_version: "atlas.connector-target-configuration-binding.v1",
  version: 1,
  source_instance_record_id: instance.record_id,
  source_instance_record_digest: instance.canonical_digest,
  organization_id: instance.organization_id,
  environment_id: instance.environment_id,
  package_digest: instance.package_digest,
  connector_id: instance.connector_id,
  release_version: instance.release_version,
  manifest_digest: instance.manifest_digest,
  instance_id: instance.instance_id,
  instance_key: instance.instance_key,
  display_name: instance.display_name,
  owner_id: instance.owner_id,
  target_profile_id: "connector-target-profile.development-storage",
  target_profile_digest:
    "ac24f2f42d0e4abb3bc1cc88786c703aea9b1402694864b6fba59dedd946d8b1",
  site_id: "site.local",
  target_type: "target-type.storage-management",
  target_product: "Synthetic Storage",
  target_version: "version.10.9",
  configuration_policy_id: "connector-target-configuration-policy.development",
  configuration_policy_digest:
    "65f94e1f98af78dd52245ccd1da1f841aeb3ac89511fcea69eb9c594143a4a2d",
  configuration_policy_version: "version.1.0",
  configuration_version: 1,
  instance_state: "disabled_target_configured",
  bound_by: "subject.connector-independent-target-configurator",
  purpose: "Bind signed target configuration without runtime authority.",
  bound_at: "2026-08-06T00:00:00Z",
  canonical_digest: "9".repeat(64),
  package_installed: true,
  instance_created: true,
  target_configured: true,
  eligible_for_credential_governance: true,
  promotion_blocked: false,
  credentials_resolved: false,
  connector_enabled: false,
  runtime_trust_granted: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorTargetConfigurationBinding;
