import type {
  ConnectorSecretBrokerageAuthorizationInventoryItem,
  ConnectorSecretBrokerageAuthorizationOption,
} from "../../api/secretBrokerageAuthorizations";
import { runtimeTrustGrantInventoryItem } from "./testRuntimeTrustFixture";

export const secretBrokerageAuthorizationOption = {
  source_runtime_trust_grant_id: runtimeTrustGrantInventoryItem.grant_id,
  source_runtime_trust_digest: "1".repeat(64),
  package_digest: "2".repeat(64),
  brokerage_profile_id: "connector-secret-brokerage-profile.memory-only-read-only",
  brokerage_profile_digest: "4".repeat(64),
  brokerage_profile_expires_at: "2030-01-01T00:00:00Z",
  delivery_policy_id: "secret-delivery-policy.memory-only",
  lease_policy_id: "secret-lease-policy.single-use-non-renewable",
  maximum_lease_seconds: 300,
  revocation_policy_id: "secret-revocation-policy.check-before-issue-and-use",
  brokerage_policy_id: "connector-secret-brokerage-policy.development",
  brokerage_policy_digest: "5".repeat(64),
  brokerage_policy_version: "policy-v1",
  brokerage_policy_expires_at: "2030-01-01T00:00:00Z",
  required_assurance_level: "single_factor",
  resulting_instance_state: "enabled_secret_brokerage_governed",
  secret_brokerage_governed: true,
  credential_resolution_authorized: true,
  eligible_for_runtime_activation: true,
  secret_lease_issued: false,
  credentials_resolved: false,
  runner_started: false,
  package_loaded: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorSecretBrokerageAuthorizationOption;

export const secretBrokerageAuthorizationInventoryItem = {
  authorization_id: "connector-secret-brokerage-authorization.test",
  source_runtime_trust_grant_id: runtimeTrustGrantInventoryItem.grant_id,
  connector_id: runtimeTrustGrantInventoryItem.connector_id,
  release_version: runtimeTrustGrantInventoryItem.release_version,
  instance_id: runtimeTrustGrantInventoryItem.instance_id,
  display_name: runtimeTrustGrantInventoryItem.display_name,
  credential_class: "credential.api-token",
  authentication_method: "auth.api-token",
  privilege_class: "privilege.read-only",
  rotation_state: "rotation.current",
  revocation_state: "revocation.active",
  next_rotation_at: "2030-01-01T00:00:00Z",
  runtime_profile_id: runtimeTrustGrantInventoryItem.runtime_profile_id,
  brokerage_profile_id: secretBrokerageAuthorizationOption.brokerage_profile_id,
  delivery_policy_id: secretBrokerageAuthorizationOption.delivery_policy_id,
  lease_policy_id: secretBrokerageAuthorizationOption.lease_policy_id,
  maximum_lease_seconds: secretBrokerageAuthorizationOption.maximum_lease_seconds,
  revocation_policy_id: secretBrokerageAuthorizationOption.revocation_policy_id,
  brokerage_policy_id: secretBrokerageAuthorizationOption.brokerage_policy_id,
  brokerage_policy_version: secretBrokerageAuthorizationOption.brokerage_policy_version,
  authorization_version: 1,
  instance_state: "enabled_secret_brokerage_governed",
  authorized_by: "subject.connector-secret-brokerage-authorizer",
  purpose: "Authorize exact future memory-only secret brokerage without issuing a lease.",
  authorized_at: "2026-08-24T00:00:00Z",
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  eligible_for_secret_brokerage: true,
  secret_brokerage_governed: true,
  credential_resolution_authorized: true,
  eligible_for_runtime_activation: true,
  promotion_blocked: false,
  secret_lease_issued: false,
  credentials_resolved: false,
  runner_started: false,
  package_loaded: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorSecretBrokerageAuthorizationInventoryItem;
