import type { ConnectorCapabilityEnablement } from "../../api/capabilityEnablements";
import { configurationValidation } from "./testConfigurationValidationFixture";

export const capabilityProfileDigest = "d".repeat(64);
export const capabilityPolicyDigest = "3037f7c378ac3046e92be04e9b71015d63780b6ce961de131e02b13b788da438";

export const capabilityEnablement = {
  enablement_id: "connector-capability-enablement.test",
  schema_version: "atlas.connector-capability-enablement.v1",
  version: 1,
  source_validation_id: configurationValidation.validation_id,
  source_validation_digest: configurationValidation.canonical_digest,
  organization_id: configurationValidation.organization_id,
  environment_id: configurationValidation.environment_id,
  package_digest: configurationValidation.package_digest,
  connector_id: configurationValidation.connector_id,
  release_version: configurationValidation.release_version,
  manifest_digest: configurationValidation.manifest_digest,
  instance_id: configurationValidation.instance_id,
  instance_key: configurationValidation.instance_key,
  display_name: configurationValidation.display_name,
  owner_id: configurationValidation.owner_id,
  target_profile_id: configurationValidation.target_profile_id,
  target_profile_digest: configurationValidation.target_profile_digest,
  site_id: configurationValidation.site_id,
  target_type: configurationValidation.target_type,
  target_product: configurationValidation.target_product,
  credential_profile_id: configurationValidation.credential_profile_id,
  credential_profile_digest: configurationValidation.credential_profile_digest,
  capability_profile_id: "connector-capability-profile.development-read-only",
  capability_profile_digest: capabilityProfileDigest,
  capabilities: [
    {
      capability_id: "health.read",
      capability_class: "C1",
      required_permission: "connector.health.read",
    },
  ],
  enablement_policy_id: "connector-capability-enablement-policy.development",
  enablement_policy_digest: capabilityPolicyDigest,
  enablement_policy_version: "policy-v1",
  enablement_version: 1,
  instance_state: "enabled_capabilities_governed",
  enabled_by: "subject.connector-capability-enabler",
  purpose: "Enable governed read-only capability metadata without runtime authority.",
  enabled_at: "2026-08-06T00:00:00Z",
  canonical_digest: "e".repeat(64),
  configuration_validated: true,
  connectivity_evidence_verified: true,
  eligible_for_capability_governance: true,
  capability_governance_applied: true,
  connector_enabled: true,
  eligible_for_runtime_trust: true,
  promotion_blocked: false,
  credentials_resolved: false,
  runtime_trust_granted: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorCapabilityEnablement;
