import type {
  ConnectorRuntimeTrustGrant,
  ConnectorRuntimeTrustGrantInventoryItem,
  ConnectorRuntimeTrustGrantOption,
} from "../../api/runtimeTrustGrants";
import {
  capabilityEnablement,
  capabilityEnablementInventoryItem,
} from "./testCapabilityEnablementFixture";

export const runtimeProfileDigest = "a".repeat(64);
export const runtimePolicyDigest = "b".repeat(64);

export const runtimeTrustGrantOption = {
  source_enablement_id: capabilityEnablementInventoryItem.enablement_id,
  source_enablement_digest: "c".repeat(64),
  package_digest: "d".repeat(64),
  runtime_profile_id: "connector-runtime-trust-profile.development-isolated-read-only",
  runtime_profile_digest: runtimeProfileDigest,
  runtime_profile_expires_at: "2030-01-01T00:00:00Z",
  sdk_profile: "atlas.python312.v1",
  runner_runtime_id: "runner-runtime.python312",
  runner_image_digest: "e".repeat(64),
  runner_workload_identity_id: "workload.connector-runner.read-only",
  isolation_profile_id: "isolation-profile.process-restricted",
  filesystem_policy_id: "filesystem-policy.package-read-only",
  egress_policy_id: "egress-policy.target-bound-disabled-until-invocation",
  telemetry_policy_id: "telemetry-policy.connector-redacted",
  resource_limit_profile_id: "resource-limit-profile.connector-read-only",
  trust_policy_id: "connector-runtime-trust-policy.development",
  trust_policy_digest: runtimePolicyDigest,
  trust_policy_version: "policy-v1",
  trust_policy_expires_at: "2030-01-01T00:00:00Z",
  required_assurance_level: "single_factor",
  resulting_instance_state: "enabled_runtime_trusted",
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  eligible_for_secret_brokerage: true,
  runner_started: false,
  package_loaded: false,
  credential_resolution_authorized: false,
  credentials_resolved: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorRuntimeTrustGrantOption;

export const runtimeTrustGrantInventoryItem = {
  grant_id: "connector-runtime-trust-grant.test",
  source_enablement_id: capabilityEnablementInventoryItem.enablement_id,
  connector_id: capabilityEnablementInventoryItem.connector_id,
  release_version: capabilityEnablementInventoryItem.release_version,
  instance_id: capabilityEnablementInventoryItem.instance_id,
  display_name: capabilityEnablementInventoryItem.display_name,
  capability_profile_id: capabilityEnablementInventoryItem.capability_profile_id,
  capability_count: capabilityEnablementInventoryItem.capabilities.length,
  runtime_profile_id: runtimeTrustGrantOption.runtime_profile_id,
  sdk_profile: runtimeTrustGrantOption.sdk_profile,
  runner_runtime_id: runtimeTrustGrantOption.runner_runtime_id,
  runner_image_digest: runtimeTrustGrantOption.runner_image_digest,
  runner_workload_identity_id: runtimeTrustGrantOption.runner_workload_identity_id,
  isolation_profile_id: runtimeTrustGrantOption.isolation_profile_id,
  filesystem_policy_id: runtimeTrustGrantOption.filesystem_policy_id,
  egress_policy_id: runtimeTrustGrantOption.egress_policy_id,
  telemetry_policy_id: runtimeTrustGrantOption.telemetry_policy_id,
  resource_limit_profile_id: runtimeTrustGrantOption.resource_limit_profile_id,
  trust_policy_id: runtimeTrustGrantOption.trust_policy_id,
  trust_policy_version: runtimeTrustGrantOption.trust_policy_version,
  trust_version: 1,
  instance_state: "enabled_runtime_trusted",
  granted_by: "subject.connector-runtime-trust-granter",
  purpose: "Bind the exact enabled connector to an isolated runtime without starting it.",
  granted_at: "2026-08-24T00:00:00Z",
  configuration_validated: true,
  connectivity_evidence_verified: true,
  capability_governance_applied: true,
  connector_enabled: true,
  eligible_for_runtime_trust: true,
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  eligible_for_secret_brokerage: true,
  runner_started: false,
  package_loaded: false,
  credential_resolution_authorized: false,
  credentials_resolved: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorRuntimeTrustGrantInventoryItem;

export const runtimeTrustGrant = {
  grant_id: runtimeTrustGrantInventoryItem.grant_id,
  schema_version: "atlas.connector-runtime-trust-grant.v1",
  version: 1,
  source_enablement_id: capabilityEnablement.enablement_id,
  source_enablement_digest: capabilityEnablement.canonical_digest,
  organization_id: capabilityEnablement.organization_id,
  environment_id: capabilityEnablement.environment_id,
  package_digest: capabilityEnablement.package_digest,
  connector_id: capabilityEnablement.connector_id,
  release_version: capabilityEnablement.release_version,
  manifest_digest: capabilityEnablement.manifest_digest,
  instance_id: capabilityEnablement.instance_id,
  instance_key: capabilityEnablement.instance_key,
  display_name: capabilityEnablement.display_name,
  capability_profile_id: capabilityEnablement.capability_profile_id,
  capability_profile_digest: capabilityEnablement.capability_profile_digest,
  capability_count: capabilityEnablement.capabilities.length,
  runtime_profile_id: runtimeTrustGrantOption.runtime_profile_id,
  runtime_profile_digest: runtimeTrustGrantOption.runtime_profile_digest,
  sdk_profile: runtimeTrustGrantOption.sdk_profile,
  runner_runtime_id: runtimeTrustGrantOption.runner_runtime_id,
  runner_pool_id: "runner-pool.development-isolated",
  runner_image_digest: runtimeTrustGrantOption.runner_image_digest,
  runner_workload_identity_id: runtimeTrustGrantOption.runner_workload_identity_id,
  isolation_profile_id: runtimeTrustGrantOption.isolation_profile_id,
  filesystem_policy_id: runtimeTrustGrantOption.filesystem_policy_id,
  egress_policy_id: runtimeTrustGrantOption.egress_policy_id,
  secret_delivery_policy_id: "secret-delivery-policy.ephemeral-disabled-until-brokered",
  telemetry_policy_id: runtimeTrustGrantOption.telemetry_policy_id,
  resource_limit_profile_id: runtimeTrustGrantOption.resource_limit_profile_id,
  trust_policy_id: runtimeTrustGrantOption.trust_policy_id,
  trust_policy_digest: runtimeTrustGrantOption.trust_policy_digest,
  trust_policy_version: runtimeTrustGrantOption.trust_policy_version,
  trust_version: 1,
  instance_state: "enabled_runtime_trusted",
  granted_by: runtimeTrustGrantInventoryItem.granted_by,
  purpose: runtimeTrustGrantInventoryItem.purpose,
  granted_at: runtimeTrustGrantInventoryItem.granted_at,
  canonical_digest: "f".repeat(64),
  configuration_validated: true,
  connectivity_evidence_verified: true,
  capability_governance_applied: true,
  connector_enabled: true,
  eligible_for_runtime_trust: true,
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  eligible_for_secret_brokerage: true,
  promotion_blocked: false,
  runner_started: false,
  package_loaded: false,
  credential_resolution_authorized: false,
  credentials_resolved: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorRuntimeTrustGrant;
