import type { ConnectorInstanceRecord } from "../../api/connectorInstances";
import { installationReceipt as receipt } from "./testInstallationFixture";

export const connectorInstanceRecord = {
  record_id: "connector-instance-record.test",
  schema_version: "atlas.connector-instance-record.v1",
  version: 1,
  source_installation_receipt_id: receipt.receipt_id,
  source_installation_receipt_digest: receipt.canonical_digest,
  organization_id: receipt.organization_id,
  environment_id: receipt.environment_id,
  package_digest: receipt.package_digest,
  connector_id: receipt.connector_id,
  release_version: receipt.release_version,
  manifest_digest: receipt.manifest_digest,
  sdk_profile: receipt.sdk_profile,
  instance_policy_id: "connector-instance-creation-policy.development",
  instance_policy_digest:
    "f26624c1e18a25c13bc8cf7d29aed3d17d1ff0d3949a47af422fe1f256fb5401",
  instance_policy_version: "version.1.0",
  instance_id: "connector-instance.test",
  instance_key: "storage-east",
  display_name: "Storage East",
  instance_state: "disabled_unconfigured",
  owner_id: "subject.connector-independent-instance-creator",
  support_group_id: "group.connector-platform-support",
  created_by: "subject.connector-independent-instance-creator",
  purpose: "Create a disabled connector instance without target or runtime authority.",
  created_at: "2026-08-06T00:00:00Z",
  canonical_digest: "8".repeat(64),
  package_published: true,
  connector_registered: true,
  package_installed: true,
  instance_created: true,
  eligible_for_configuration_governance: true,
  promotion_blocked: false,
  target_configured: false,
  credentials_resolved: false,
  connector_enabled: false,
  runtime_trust_granted: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorInstanceRecord;
