import type {
  OperationalEvidenceKnowledgeDraftInventoryItem,
  OperationalEvidenceKnowledgeDraftOption,
} from "../../api/evidenceDrafts";
import { invocationEvidenceInventoryItem } from "./testInvocationEvidenceFixture";

export const evidenceKnowledgeDraftOption = {
  curation_option_id: "operational-evidence-knowledge-draft-option.test",
  source_ingestion_id: invocationEvidenceInventoryItem.ingestion_id,
  source_ingestion_digest: invocationEvidenceInventoryItem.canonical_digest,
  evidence_package_id: invocationEvidenceInventoryItem.evidence_package_id,
  capability_id: invocationEvidenceInventoryItem.capability_id,
  curation_policy_id: "operational-evidence-knowledge-draft-policy.development",
  curation_policy_digest: "b".repeat(64),
  curation_policy_version: "policy-v1",
  curation_policy_expires_at: "2030-01-01T01:00:00Z",
  required_assurance_level: "single_factor",
  classification: invocationEvidenceInventoryItem.classification,
  access_policy_id: "access-policy.operational-evidence-draft",
  retention_policy_id: invocationEvidenceInventoryItem.retention_policy_id,
  maximum_draft_items: 100,
  maximum_draft_bytes: 262144,
  resulting_instance_state: "draft_operational_knowledge_created",
  irreversible_claim_required: true,
  automatic_retry_allowed: false,
  review_requested: false,
  knowledge_approved: false,
  knowledge_published: false,
  retrieval_published: false,
  model_context_available: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies OperationalEvidenceKnowledgeDraftOption;

export const evidenceKnowledgeDraftInventoryItem = {
  draft_id: "operational-evidence-knowledge-draft.test",
  schema_version: "atlas.operational-evidence-knowledge-draft.v1",
  version: 1,
  source_ingestion_id: invocationEvidenceInventoryItem.ingestion_id,
  source_ingestion_digest: invocationEvidenceInventoryItem.canonical_digest,
  evidence_package_id: invocationEvidenceInventoryItem.evidence_package_id,
  connector_id: "connector.test",
  instance_id: "connector-instance.test",
  capability_id: invocationEvidenceInventoryItem.capability_id,
  title: "Test connector operational evidence",
  knowledge_lifecycle: "draft",
  classification: invocationEvidenceInventoryItem.classification,
  retention_policy_id: invocationEvidenceInventoryItem.retention_policy_id,
  retention_policy_digest: invocationEvidenceInventoryItem.retention_policy_digest,
  curation_policy_id: evidenceKnowledgeDraftOption.curation_policy_id,
  curation_policy_digest: evidenceKnowledgeDraftOption.curation_policy_digest,
  curation_policy_version: evidenceKnowledgeDraftOption.curation_policy_version,
  draft_item_count: 1,
  draft_bytes: 256,
  observed_from: invocationEvidenceInventoryItem.observed_from,
  observed_to: invocationEvidenceInventoryItem.observed_to,
  created_at: "2026-08-25T00:00:07Z",
  instance_state: "draft_operational_knowledge_created",
  canonical_digest: "c".repeat(64),
  evidence_ingested: true,
  knowledge_item_created: true,
  immutable_draft_confirmed: true,
  encrypted_at_rest: true,
  transient_buffers_erased: true,
  artifact_channel_closed: true,
  domain_review_completed: false,
  security_review_completed: false,
  knowledge_approved: false,
  knowledge_published: false,
  chunks_created: false,
  embeddings_created: false,
  retrieval_published: false,
  model_context_available: false,
  graph_updated: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies OperationalEvidenceKnowledgeDraftInventoryItem;
