import type {
  ConnectorInvocationAuthorizationInventoryItem,
  ConnectorInvocationAuthorizationOption,
} from "../../api/invocationAuthorizations";
import { targetSessionVerificationInventoryItem } from "./testTargetSessionFixture";

export const invocationAuthorizationOption = {
  source_target_session_verification_id: targetSessionVerificationInventoryItem.verification_id,
  source_target_session_digest: targetSessionVerificationInventoryItem.canonical_digest,
  package_digest: "a".repeat(64),
  capability_id: "capability.storage.health.read",
  capability_class: "C1",
  required_permission: "storage.health.read",
  invocation_profile_id: "connector-invocation-profile.synthetic-read-only",
  invocation_profile_digest: "b".repeat(64),
  invocation_profile_expires_at: "2030-01-01T00:00:00Z",
  input_envelope_id: "connector-invocation-input-envelope.synthetic-empty",
  input_envelope_digest: "c".repeat(64),
  input_envelope_expires_at: "2030-01-01T00:00:00Z",
  input_envelope_field_count: 0,
  authorization_policy_id: "connector-invocation-authorization-policy.development",
  authorization_policy_digest: "d".repeat(64),
  authorization_policy_version: "policy-v1",
  authorization_policy_expires_at: "2030-01-01T00:00:00Z",
  required_assurance_level: "single_factor",
  maximum_timeout_seconds: 30,
  maximum_output_bytes: 262144,
  resulting_instance_state: "enabled_capability_invocation_governed",
  capability_invocation_authorized: true,
  eligible_for_bounded_capability_invocation: true,
  single_use: true,
  renewable: false,
  consumed: false,
  target_connected: false,
  capability_invoked: false,
  scheduled: false,
  result_received: false,
  result_validated: false,
  evidence_ingested: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorInvocationAuthorizationOption;

export const invocationAuthorizationInventoryItem = {
  authorization_id: "connector-invocation-authorization.test",
  schema_version: "atlas.connector-invocation-authorization.v1",
  version: 1,
  source_target_session_verification_id:
    targetSessionVerificationInventoryItem.verification_id,
  capability_id: invocationAuthorizationOption.capability_id,
  capability_class: invocationAuthorizationOption.capability_class,
  invocation_profile_digest: invocationAuthorizationOption.invocation_profile_digest,
  input_envelope_digest: invocationAuthorizationOption.input_envelope_digest,
  authorization_policy_digest: invocationAuthorizationOption.authorization_policy_digest,
  instance_state: "enabled_capability_invocation_governed",
  authorized_at: "2026-08-24T00:00:03Z",
  expires_at: "2030-01-01T00:15:00Z",
  canonical_digest: "e".repeat(64),
  target_session_verified: true,
  capability_enabled: true,
  capability_permission_verified: true,
  capability_invocation_authorized: true,
  eligible_for_bounded_capability_invocation: true,
  single_use: true,
  renewable: false,
  consumed: false,
  target_connected: false,
  capability_invoked: false,
  scheduled: false,
  result_received: false,
  result_validated: false,
  evidence_ingested: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorInvocationAuthorizationInventoryItem;
