import type {
  ConnectorInvocationEvidenceInventoryItem,
  ConnectorInvocationEvidenceOption,
} from "../../api/invocationEvidence";
import { boundedInvocationInventoryItem } from "./testBoundedInvocationFixture";

export const invocationEvidenceOption = {
  source_invocation_id: boundedInvocationInventoryItem.invocation_id,
  source_invocation_digest: boundedInvocationInventoryItem.canonical_digest,
  capability_id: boundedInvocationInventoryItem.capability_id,
  capability_class: boundedInvocationInventoryItem.capability_class,
  required_permission: boundedInvocationInventoryItem.required_permission,
  ingestion_policy_id: "connector-invocation-evidence-policy.development",
  ingestion_policy_digest: "4".repeat(64),
  ingestion_policy_version: "policy-v1",
  ingestion_policy_expires_at: "2030-01-01T01:00:00Z",
  classification: "classification.internal",
  retention_policy_id: "retention-policy.connector-evidence",
  required_assurance_level: "single_factor",
  maximum_evidence_items: 100,
  maximum_evidence_bytes: 262144,
  resulting_instance_state: "enabled_invocation_evidence_ingested",
  irreversible_claim_required: true,
  automatic_retry_allowed: false,
  knowledge_item_created: false,
  retrieval_published: false,
  model_context_available: false,
  graph_updated: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorInvocationEvidenceOption;

export const invocationEvidenceInventoryItem = {
  ingestion_id: "connector-invocation-evidence-ingestion.test",
  schema_version: "atlas.connector-invocation-evidence-ingestion.v1",
  version: 1,
  source_invocation_id: boundedInvocationInventoryItem.invocation_id,
  source_invocation_digest: boundedInvocationInventoryItem.canonical_digest,
  package_digest: boundedInvocationInventoryItem.package_digest,
  capability_id: boundedInvocationInventoryItem.capability_id,
  capability_class: boundedInvocationInventoryItem.capability_class,
  required_permission: boundedInvocationInventoryItem.required_permission,
  normalized_redacted_result_digest:
    boundedInvocationInventoryItem.normalized_redacted_result_digest,
  evidence_package_id: "connector-evidence-package.test",
  evidence_schema_version: "atlas.connector-evidence-package.v1",
  evidence_content_digest: "8".repeat(64),
  evidence_metadata_digest: "9".repeat(64),
  classification: invocationEvidenceOption.classification,
  retention_policy_id: invocationEvidenceOption.retention_policy_id,
  retention_policy_digest: "6".repeat(64),
  ingestion_policy_id: invocationEvidenceOption.ingestion_policy_id,
  ingestion_policy_digest: invocationEvidenceOption.ingestion_policy_digest,
  ingestion_policy_version: invocationEvidenceOption.ingestion_policy_version,
  evidence_item_count: 1,
  evidence_bytes: 256,
  observed_from: "2026-08-25T00:00:04Z",
  observed_to: "2026-08-25T00:00:04.025Z",
  ingested_at: "2026-08-25T00:00:05Z",
  instance_state: "enabled_invocation_evidence_ingested",
  canonical_digest: "a".repeat(64),
  source_invocation_completed: true,
  evidence_ingested: true,
  immutable_storage_confirmed: true,
  encrypted_at_rest: true,
  transient_buffers_erased: true,
  artifact_channel_closed: true,
  knowledge_item_created: false,
  retrieval_published: false,
  model_context_available: false,
  graph_updated: false,
  scheduled: false,
  workflow_continued: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorInvocationEvidenceInventoryItem;
