import type { ConnectorRuntimeTrustGrant } from "../../api/runtimeTrustGrants";
import { capabilityEnablement } from "./testCapabilityEnablementFixture";

export const runtimeProfileDigest = "a".repeat(64);
export const runtimePolicyDigest = "42157b3d8b23514b4f754a2f0f9f507122c6718289a2ae8986e226287d718d33";

export const runtimeTrustGrant = {
  grant_id: "connector-runtime-trust-grant.test",
  schema_version: "atlas.connector-runtime-trust-grant.v1",
  version: 1,
  source_enablement_id: capabilityEnablement.enablement_id,
  source_enablement_digest: capabilityEnablement.canonical_digest,
  organization_id: capabilityEnablement.organization_id,
  environment_id: capabilityEnablement.environment_id,
  package_digest: capabilityEnablement.package_digest,
  connector_id: capabilityEnablement.connector_id,
  release_version: capabilityEnablement.release_version,
  manifest_digest: capabilityEnablement.manifest_digest,
  instance_id: capabilityEnablement.instance_id,
  instance_key: capabilityEnablement.instance_key,
  display_name: capabilityEnablement.display_name,
  capability_profile_id: capabilityEnablement.capability_profile_id,
  capability_profile_digest: capabilityEnablement.capability_profile_digest,
  capability_count: capabilityEnablement.capabilities.length,
  runtime_profile_id: "connector-runtime-trust-profile.development-isolated-read-only",
  runtime_profile_digest: runtimeProfileDigest,
  sdk_profile: "atlas.python312.v1",
  runner_runtime_id: "runner-runtime.python312",
  runner_pool_id: "runner-pool.development-isolated",
  runner_image_digest: "b".repeat(64),
  runner_workload_identity_id: "workload.connector-runner.read-only",
  isolation_profile_id: "isolation-profile.process-restricted",
  filesystem_policy_id: "filesystem-policy.package-read-only",
  egress_policy_id: "egress-policy.target-bound-disabled-until-invocation",
  secret_delivery_policy_id: "secret-delivery-policy.ephemeral-disabled-until-brokered",
  telemetry_policy_id: "telemetry-policy.connector-redacted",
  resource_limit_profile_id: "resource-limit-profile.connector-read-only",
  trust_policy_id: "connector-runtime-trust-policy.development",
  trust_policy_digest: runtimePolicyDigest,
  trust_policy_version: "policy-v1",
  trust_version: 1,
  instance_state: "enabled_runtime_trusted",
  granted_by: "subject.connector-runtime-trust-granter",
  purpose: "Bind the exact enabled connector to an isolated runtime without starting it.",
  granted_at: "2026-08-06T00:00:00Z",
  canonical_digest: "c".repeat(64),
  configuration_validated: true,
  connectivity_evidence_verified: true,
  capability_governance_applied: true,
  connector_enabled: true,
  eligible_for_runtime_trust: true,
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  eligible_for_secret_brokerage: true,
  promotion_blocked: false,
  runner_started: false,
  package_loaded: false,
  credential_resolution_authorized: false,
  credentials_resolved: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorRuntimeTrustGrant;
