import type { ConnectorRuntimeActivation } from "../../api/runtimeActivations";
import type { ConnectorSecretBrokerageAuthorization } from "../../api/secretBrokerageAuthorizations";
import type {
  ConnectorTargetSessionVerificationInventoryItem,
  ConnectorTargetSessionVerificationOption,
} from "../../api/targetSessionVerifications";
import { runtimeTrustGrant } from "./testRuntimeTrustFixture";
import { runtimeActivationInventoryItem } from "./testRuntimeActivationFixture";

const brokerage = {
  authorization_id: "connector-secret-brokerage-authorization.test",
  schema_version: "atlas.connector-secret-brokerage-authorization.v1",
  version: 1,
  source_runtime_trust_grant_id: runtimeTrustGrant.grant_id,
  source_runtime_trust_digest: runtimeTrustGrant.canonical_digest,
  organization_id: runtimeTrustGrant.organization_id,
  environment_id: runtimeTrustGrant.environment_id,
  package_digest: runtimeTrustGrant.package_digest,
  connector_id: runtimeTrustGrant.connector_id,
  release_version: runtimeTrustGrant.release_version,
  manifest_digest: runtimeTrustGrant.manifest_digest,
  instance_id: runtimeTrustGrant.instance_id,
  instance_key: runtimeTrustGrant.instance_key,
  display_name: runtimeTrustGrant.display_name,
  credential_class: "credential.api-token",
  authentication_method: "auth.api-token",
  privilege_class: "privilege.read-only",
  rotation_state: "rotation.current",
  revocation_state: "revocation.active",
  next_rotation_at: "2026-08-09T13:00:00Z",
  runtime_profile_id: runtimeTrustGrant.runtime_profile_id,
  runtime_profile_digest: runtimeTrustGrant.runtime_profile_digest,
  runner_workload_identity_id: runtimeTrustGrant.runner_workload_identity_id,
  secret_delivery_policy_id: runtimeTrustGrant.secret_delivery_policy_id,
  brokerage_profile_id: "connector-secret-brokerage-profile.development-memory-only",
  brokerage_profile_digest: "f".repeat(64),
  delivery_policy_id: runtimeTrustGrant.secret_delivery_policy_id,
  lease_policy_id: "secret-lease-policy.single-use-non-renewable",
  maximum_lease_seconds: 300,
  revocation_policy_id: "secret-revocation-policy.check-before-issue-and-use",
  brokerage_policy_id: "connector-secret-brokerage-policy.development",
  brokerage_policy_digest: "a".repeat(64),
  brokerage_policy_version: "policy-v1",
  authorization_version: 1,
  instance_state: "enabled_secret_brokerage_governed",
  authorized_by: "subject.connector-secret-brokerage-authorizer",
  purpose: "Authorize exact future memory-only secret brokerage without issuing a lease.",
  authorized_at: "2026-08-06T00:00:00Z",
  canonical_digest: "9".repeat(64),
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  eligible_for_secret_brokerage: true,
  secret_brokerage_governed: true,
  credential_resolution_authorized: true,
  eligible_for_runtime_activation: true,
  promotion_blocked: false,
  secret_lease_issued: false,
  credentials_resolved: false,
  runner_started: false,
  package_loaded: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorSecretBrokerageAuthorization;

export const activation = {
  activation_id: "connector-runtime-activation.test",
  schema_version: "atlas.connector-runtime-activation.v1",
  version: 1,
  source_brokerage_authorization_id: brokerage.authorization_id,
  source_brokerage_authorization_digest: brokerage.canonical_digest,
  organization_id: brokerage.organization_id,
  environment_id: brokerage.environment_id,
  package_digest: brokerage.package_digest,
  connector_id: brokerage.connector_id,
  release_version: brokerage.release_version,
  manifest_digest: brokerage.manifest_digest,
  instance_id: brokerage.instance_id,
  instance_key: brokerage.instance_key,
  display_name: brokerage.display_name,
  runtime_profile_digest: brokerage.runtime_profile_digest,
  runner_identity_digest: "1".repeat(64),
  image_digest: "2".repeat(64),
  workload_identity_digest: "3".repeat(64),
  activation_profile_id: "connector-runtime-activation-profile.development-synthetic",
  activation_profile_digest: "e".repeat(64),
  activation_policy_id: "connector-runtime-activation-policy.development",
  activation_policy_digest: "d".repeat(64),
  activation_policy_version: "policy-v1",
  activation_adapter_id: "connector-runtime-activator.synthetic",
  health_probe_results: [
    { probe_id: "health.package-loaded", outcome: "health.passed" },
    { probe_id: "health.runtime-responsive", outcome: "health.passed" },
  ],
  instance_state: "enabled_runtime_healthy",
  activated_by: "subject.connector-runtime-activation-operator",
  purpose: "Activate the exact isolated connector runtime and verify local health only.",
  activated_at: "2026-08-06T00:00:00Z",
  healthy_at: "2026-08-06T00:00:01Z",
  canonical_digest: "8".repeat(64),
  runtime_boundary_bound: true,
  runtime_trust_granted: true,
  secret_brokerage_governed: true,
  credential_resolution_authorized: true,
  secret_lease_issued: true,
  credentials_resolved: true,
  runner_started: true,
  package_loaded: true,
  runtime_health_verified: true,
  lease_delivery_completed: true,
  delivery_channel_closed: true,
  lease_revocation_confirmed: true,
  eligible_for_target_session_authorization: true,
  target_connected: false,
  target_connection_authorized: false,
  capability_invocation_authorized: false,
  capability_invoked: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
  reused: false,
} satisfies ConnectorRuntimeActivation;

export const targetSessionVerificationOption = {
  source_runtime_activation_id: runtimeActivationInventoryItem.activation_id,
  source_runtime_activation_digest: "4".repeat(64),
  package_digest: "5".repeat(64),
  session_profile_id: "connector-target-session-profile.synthetic-read-only",
  session_profile_digest: "6".repeat(64),
  session_profile_expires_at: "2030-01-01T00:00:00Z",
  session_policy_id: "connector-target-session-policy.development",
  session_policy_digest: "7".repeat(64),
  session_policy_version: "policy-v1",
  session_policy_expires_at: "2030-01-01T00:00:00Z",
  expected_target_product: "Synthetic read-only storage",
  protocol_classification: "protocol.https-read-only",
  connectivity_check_ids: [
    "connectivity.authentication",
    "connectivity.read-only-privilege",
    "connectivity.target-identity",
    "connectivity.tls",
  ],
  required_assurance_level: "single_factor",
  resulting_instance_state: "enabled_target_session_verified",
  target_connection_authorized: true,
  target_connectivity_verified: true,
  target_identity_verified: true,
  read_only_session_verified: true,
  target_session_closed: true,
  delivery_channel_closed: true,
  lease_revocation_confirmed: true,
  eligible_for_capability_invocation_governance: true,
  target_connected: false,
  capability_invocation_authorized: false,
  capability_invoked: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorTargetSessionVerificationOption;

export const targetSessionVerificationInventoryItem = {
  verification_id: "connector-target-session-verification.test",
  schema_version: "atlas.connector-target-session-verification.v1",
  version: 1,
  source_runtime_activation_id: runtimeActivationInventoryItem.activation_id,
  target_identity_digest: "8".repeat(64),
  protocol_classification: targetSessionVerificationOption.protocol_classification,
  tls_classification: "tls.1-3-verified",
  session_profile_digest: targetSessionVerificationOption.session_profile_digest,
  session_policy_digest: targetSessionVerificationOption.session_policy_digest,
  connectivity_check_results: targetSessionVerificationOption.connectivity_check_ids.map(
    (check_id) => ({ check_id, outcome: "connectivity.passed" as const }),
  ),
  instance_state: "enabled_target_session_verified",
  verified_at: "2026-08-24T00:00:02Z",
  canonical_digest: "9".repeat(64),
  runtime_health_verified: true,
  secret_brokerage_governed: true,
  target_connection_authorized: true,
  target_connectivity_verified: true,
  target_identity_verified: true,
  read_only_session_verified: true,
  target_session_established: true,
  target_session_closed: true,
  delivery_channel_closed: true,
  lease_revocation_confirmed: true,
  eligible_for_capability_invocation_governance: true,
  target_connected: false,
  capability_invocation_authorized: false,
  capability_invoked: false,
  scheduled: false,
  execution_authorized: false,
  deployment_approved: false,
  infrastructure_mutation_performed: false,
} satisfies ConnectorTargetSessionVerificationInventoryItem;
