from __future__ import annotations

from typing import Protocol

from atlas.modules.change_review.domain.completion_receipt import HumanReviewCompletionReceipt


class CompletionReceiptRepository(Protocol):
    @property
    def durable(self) -> bool: ...
    async def get_by_id(self, *, receipt_id: str) -> HumanReviewCompletionReceipt | None: ...
    async def get_by_review_id(self, *, review_id: str) -> HumanReviewCompletionReceipt | None: ...
    async def get_by_create_key(
        self, *, created_by: str, idempotency_key: str
    ) -> HumanReviewCompletionReceipt | None: ...
    async def add(self, record: HumanReviewCompletionReceipt) -> bool: ...
    async def close(self) -> None: ...
