from __future__ import annotations

from typing import Protocol

from atlas.modules.reports.domain.handoff_review import ItsmHandoffHumanReview
from atlas.modules.reports.domain.models import TechnicalReport


class TechnicalReportSource(Protocol):
    async def get(self, *, report_id: str) -> TechnicalReport | None: ...


class ItsmHandoffReviewRepository(Protocol):
    @property
    def durable(self) -> bool: ...
    async def get_by_id(self, *, review_id: str) -> ItsmHandoffHumanReview | None: ...
    async def get_by_handoff(self, *, handoff_draft_id: str) -> ItsmHandoffHumanReview | None: ...
    async def get_by_create_key(
        self, *, reviewer_id: str, idempotency_key: str
    ) -> ItsmHandoffHumanReview | None: ...
    async def add(self, review: ItsmHandoffHumanReview) -> bool: ...
    async def close(self) -> None: ...
