from __future__ import annotations

from typing import Protocol

from atlas.modules.recovery.domain.backup import BackupRecord, RestoreValidation


class RecoveryError(Exception):
    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


class RecoveryRepository(Protocol):
    @property
    def durable(self) -> bool: ...
    async def get_backup(self, *, actor_id: str, idempotency_key: str) -> BackupRecord | None: ...
    async def get_backup_by_id(self, *, actor_id: str, backup_id: str) -> BackupRecord | None: ...
    async def add_backup(self, record: BackupRecord) -> bool: ...
    async def get_validation(
        self, *, actor_id: str, idempotency_key: str
    ) -> RestoreValidation | None: ...
    async def get_validation_by_id(
        self, *, actor_id: str, validation_id: str
    ) -> RestoreValidation | None: ...
    async def add_validation(self, record: RestoreValidation) -> bool: ...
    async def close(self) -> None: ...


class BackupArchiveStore(Protocol):
    async def inspect(self, *, target_id: str, expected: bytes) -> str: ...
    async def publish(
        self, *, backup_id: str, target_id: str, expected: bytes
    ) -> tuple[str, int, str, bool]: ...
    async def read(self, *, target_id: str, max_bytes: int) -> bytes: ...
